Added calculator functions
Darlite/darlite.github.io pull request #1
Opened 2017-03-21 14:00 UTC by Darlite

2017-03-21 19:12 UTC, NikitaSedyx requested changes
don't see your function calls :)

2017-03-21 19:12 UTC, NikitaSedyx commented on calculator.js
> +function add (a, b) {
please create new folder for each task, thank you

2017-03-21 19:12 UTC, NikitaSedyx commented on calculator.js
> +}
empty line please at the EOF

2017-03-21 19:12 UTC, NikitaSedyx commented on calculator.js
> +    return a % b;
3.5 % 2 = 1.5 but intDivision should return 2

2017-03-21 23:22 UTC, Darlite commented on calculator.js
> +    return a % b;
In this case the result of integer division should be 1 because integer division doesn't round the number.

2017-03-22 05:12 UTC, NikitaSedyx approved these changes
please change spaces from 4 to 2, merge after it

2017-03-22 05:12 UTC, NikitaSedyx commented on calculator/calculator.js
> +    return parseInt(a / b);
it/s one of the way

2017-03-22 05:56 UTC, merged